auth:
  # en:
  # Instructions for retrieving the data:
  # 1. Log in to boosty.to using your account.
  # 2. Press F12 (Developer Tools) and go to the "Storage" tab.
  # 3. In the left menu, find the section "Local Storage" -> "https://boosty.to".
  # 4. In the list, find the key "auth" and copy its entire value
  #    (it starts with {%22accessToken%22...). Paste this value into the auth_data field.
  # 5. In the same place, find the key "_clientId" and copy its value into the client_id field.
  # https://ibb.co/DHTK13NQ
  # IMPORTANT: DO NOT SHARE THIS DATA WITH ANYONE!!!!

  # ru:
  # Инструкция по получению данных:
  # 1. Зайдите на boosty.to под своим аккаунтом.
  # 2. Нажмите F12 (Инструменты разработчика) и перейдите во вкладку "Storage".
  # 3. Слева в меню найдите раздел "Local Storage" -> "https://boosty.to".
  # 4. В списке найдите ключ "auth" и скопируйте его значение целиком
  #    (оно начинается с {%22accessToken%22...). Вставьте это значение в поле auth_data.
  # 5. Там же найдите ключ "_clientId" и скопируйте его значение в поле client_id.
  # https://ibb.co/DHTK13NQ
  # ВАЖНО: НИКОМУ НЕ ПЕРЕДАВАЙТЕ ЭТИ ДАННЫЕ!!!!

  auth_data: "{%22accessToken%22:%22YOUR_ACCESS_TOKEN%22%2C%22refreshToken%22:%22YOUR_REFRESH_TOKEN%22%2C%22expiresAt%22:1234567890000%2C%22isNewUser%22:false}" # replace!!
  client_id: "YOUR_CLIENT_ID" # replace!!
# ---

database:
  type: "SQLITE" # or MYSQL
  mysql: # if mysql
    host: "127.0.0.1"
    port: 3306
    database: "boosty"
    username: "root"
    password: "password"

rewards:
  "Спонсор +":
    congratulation: true # - меняется в messages.yml (congratulation_message)
    give:
      - "say спонсор+"
    take:
      - "say забран"
  "none":
    congratulation: false
    give:
      - "say %player% просто отслеживает блог!"
    take:
      - "say %player% перестал отслеживать блог!"

sync:
  # Интервал синхронизации активных подписок (в минутах)
  # Active subscriptions synchronization interval (in minutes)
  interval_minutes: 60

discord:
  enabled: false
  webhook_url: "вебхук"
  embed_color: "#FFB6C1"

  # Настройки дискорд бота
  #   Как настроить:
  #   1. Создайте бота на https://discord.com/developers/applications
  #   2. Во вкладке "Bot" скопируйте Token в поле bot_token.
  #   3. Включите Server Members Intent на той же странице.
  #   4. Пригласите бота с правом "Manage Roles"!!:
  #   5. Укажите ID вашего сервера (guild_id).
  #   6. Для каждого уровня подписки Boosty добавьте запись в "roles:",
  #   где ключ — название уровня, значение - ID роли Discord.

  bot:
    enabled: true
    token: "token"
    guild_id: 1487451822720422088 # айди сервера
    channel_id: 1503425501719695520 # айди канала для логов выдачи ролей

    roles:
      "Follower": # пример
        role_id: 1501541047279292508

# отправка кода подтверждения в личные сообщения бусти
# пользователю приходит сообщение с кодом, который он должен ввести в чат на сервере
# для завершения привязки Minecraft-аккаунта.
dm_verification:
  enabled: true
  message_template: |
    Код подтверждения привязки Minecraft-аккаунта:
    {code}

    Игрок на сервере: {player}

    Напишите этот код в чат сервера для завершения привязки.
    Если вы не инициировали привязку — проигнорируйте сообщение.

# проверять ли email пользователя (если он известен)
# если включено, email будет использоваться как резервный способ (fallback),
# если не удалось отправить сообщение в личные сообщения Boosty.
verify_email: true

debug: false
bstats: true # bStats metrics
