main: onevnl.ru.elytrya.BoostyBridge
version: a0.4
name: BoostyBridge
author: elytrya
api-version: 1.21

softdepend: [PlaceholderAPI]

commands:
  boosty:
    description: Основная команда плагина BoostyBridge
    permission: boosty.admin
permissions:
  boosty.admin:
    description: Доступ к управлению плагином
    default: op